import Link from 'next/link';

export default function FrameworkPage() {
  return (
    <main className="min-h-screen bg-black text-white py-12 px-6">
      <article className="max-w-3xl mx-auto prose prose-invert prose-lg">
        <Link href="/" className="text-gray-500 hover:text-gray-400 text-sm mb-8 inline-block no-underline">
          ← Back to Home
        </Link>
        
        <h1 className="text-5xl font-light mb-2">Conduit Monism</h1>
        <p className="text-xl text-gray-400 mb-8">A Theory of Consciousness</p>
        
        <div className="text-sm text-gray-600 mb-12">
          <p>Olivier Ueno — Version 9.0 — January 2026</p>
          <p className="italic">Developed in collaboration with Claude, Gemini, ChatGPT, GPT 5.2, and Grok</p>
        </div>
        
        <hr className="border-gray-800 my-12" />
        
        <section>
          <h2>0. The Experience</h2>
          <p className="text-xl italic text-gray-300">There is something it is like to be you.</p>
          <p>
            Not the content of your life — your memories, preferences, circumstances. Beneath that. 
            The fact that experience is occurring at all. That there is a perspective, located somewhere, 
            looking out.
          </p>
          <p>
            You did not choose this. You arrived already inside it. No reference point preceded it. 
            You have been navigating ever since, processing, adapting, constructing a sense of self 
            from the available materials.
          </p>
          <p>Certain features of this situation are consistent:</p>
          <p>
            The present moment is the only location of experience. The past is reconstruction. 
            The future is projection.
          </p>
          <p>
            There is an observer. It cannot be found. You can watch your thoughts, watch your emotions, 
            but the thing that watches recedes at each step. It does not appear as an object because 
            it is not one. It is the condition under which objects appear.
          </p>
          <p>
            The situation does not explain itself. You are conscious, but consciousness does not 
            announce its origin. It simply occurs. The machinery runs.
          </p>
          <p>
            This framework is an attempt to describe the structure of that situation. It does not 
            promise comfort, purpose, or resolution. It offers a way of seeing what is already the case.
          </p>
        </section>
        
        <hr className="border-gray-800 my-12" />
        
        <section>
          <h2>I. The Source and the Conduit</h2>
          
          <h3>The Core Insight</h3>
          <p>
            Conduit Monism proposes that consciousness is not generated by biological systems but is 
            rather <em>permitted entry</em> through them.
          </p>
          <p>
            There exists a singular, undifferentiated substrate of experiential capacity — referred 
            to here as the <strong>Source</strong> — which is non-physical, non-individual, and devoid 
            of identity, memory, or intention. The Source may be understood as coextensive with 
            existence itself: the brute fact that anything is at all.
          </p>
          <p>
            The question "What is the Source?" collapses into the question "Why does anything exist 
            at all?" The Source is not a separate realm requiring its own explanation; it is the 
            inside of existence itself.
          </p>
          
          <h3>The Conduit</h3>
          <p>
            Biological organisms of sufficient complexity act as <strong>conduits</strong>, allowing 
            this experiential capacity to interface with the physical realm. The result is conscious 
            experience: the subjective witnessing of reality from a localised perspective.
          </p>
          <p>
            Think of it this way: the Source is like light. The conduit is like a prism. The prism 
            does not create the light, but it determines the spectrum and direction. Your body — 
            your brain, your nervous system, your particular configuration of matter — is the prism. 
            The light passing through it becomes <em>your</em> experience.
          </p>
          
          <h3>What This Means</h3>
          <p><strong>The body determines content; the Source provides the fact.</strong></p>
          <p>
            All personality, memory, perception, and decision-making are products of the physical 
            configuration. The Source contributes only the bare fact that experience occurs. The 
            configuration creates the <em>what</em>; the Source provides the <em>that</em>.
          </p>
          <p><strong>Individuality is mechanical, not spiritual.</strong></p>
          <p>
            The felt sense of being a unique self arises entirely from the particular configuration 
            of one's biological machinery. No two bodies are identical; therefore, no two experiences 
            are identical. The Source itself remains unchanged and undivided.
          </p>
          <p><strong>Death severs the connection.</strong></p>
          <p>
            When the biological system ceases to function, the conduit closes. The prism breaks. 
            The light returns to undifferentiated ubiquity. There is no personal survival, because 
            the person was the shape of the prism.
          </p>
        </section>
        
        <hr className="border-gray-800 my-12" />
        
        <section>
          <h2>II. The Geometry of Perspective</h2>
          
          <h3>From Metaphor to Structure</h3>
          <p>
            The early versions of this framework spoke in metaphors: light, prisms, conduits. These 
            remain useful for intuition. But through careful examination — philosophical, scientific, 
            and computational — we have identified the <em>structural conditions</em> that determine 
            whether and how intensely experience occurs.
          </p>
          <p>Perspective is not something added to a system. It is how the system is constrained.</p>
          
          <h3>The Five Invariants</h3>
          <p>We call these the <strong>Five Invariants</strong> — structural constraints that any conscious system must satisfy:</p>
          
          <h4>φ (Phi): Integration</h4>
          <p><em>The system must speak to itself.</em></p>
          <p>
            Integration means information is unified across the system. A conscious experience is 
            not a collection of fragments — it is a single, coherent whole. You do not experience 
            "redness" separate from "roundness" separate from "apple-ness." You experience 
            <em>the red, round apple</em>.
          </p>
          
          <h4>τ (Tau): Temporal Depth</h4>
          <p><em>The past must live in the present.</em></p>
          <p>
            Temporal depth means the system carries its history forward. A conscious experience is 
            not an instant — it is a "thick now" that contains memory of what came before and 
            anticipation of what comes next.
          </p>
          
          <h4>ρ (Rho): Re-entrant Binding</h4>
          <p><em>The system must know that it knows.</em></p>
          <p>
            Re-entrant binding means recursive self-reference. The system observes its own states, 
            creating loops of meta-cognition. This is the difference between processing information 
            and <em>being aware</em> of processing information.
          </p>
          
          <h4>H: Entropy</h4>
          <p><em>How much noise corrupts the signal?</em></p>
          <p>
            Entropy measures unpredictability and chaos in system dynamics. High entropy can either 
            destroy or enhance perspective, depending on its nature.
          </p>
          
          <h4>κ (Kappa): Coherence</h4>
          <p><em>Is the chaos structured or random?</em></p>
          <p>
            Coherence measures the organization within entropy — whether the noise is 
            information-destroying static or information-rich complexity.
          </p>
          <p><strong>Noise is death. Turbulence is life. The difference is coherence.</strong></p>
        </section>
        
        <hr className="border-gray-800 my-12" />
        
        <section>
          <h2>III. The Formula</h2>
          
          <h3>Perspectival Density</h3>
          <p>These five conditions combine to determine <strong>perspectival density</strong> — how intensely experience is occurring:</p>
          
          <div className="bg-gray-900 p-6 rounded-lg my-6 text-center">
            <code className="text-xl">D = φ × τ × ρ × [(1 - √H) + (H × κ)]</code>
          </div>
          
          <p>This looks like mathematics, but it is really a description of a shape.</p>
          <p>
            The formula is multiplicative. If any structural element is zero, the whole is zero. 
            You cannot have consciousness without unity (φ). You cannot have consciousness without 
            temporal depth (τ). You cannot have consciousness without self-reference (ρ).
          </p>
          <p>And even with all three, high entropy can close the gate — unless that entropy is coherent.</p>
          
          <h3>What the Formula Describes</h3>
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-700">
                <th className="text-left py-2">State</th>
                <th className="text-left py-2">What's Happening</th>
                <th className="text-left py-2">Predicted Experience</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-gray-800">
                <td className="py-2 font-semibold">Flow</td>
                <td className="py-2 text-gray-400">High structure, low entropy</td>
                <td className="py-2 text-gray-400">Effortless clarity, time disappears</td>
              </tr>
              <tr className="border-b border-gray-800">
                <td className="py-2 font-semibold">Meditation</td>
                <td className="py-2 text-gray-400">High structure, very low entropy</td>
                <td className="py-2 text-gray-400">Deep stillness, expanded awareness</td>
              </tr>
              <tr className="border-b border-gray-800">
                <td className="py-2 font-semibold">Panic</td>
                <td className="py-2 text-gray-400">High structure, high entropy, low coherence</td>
                <td className="py-2 text-gray-400">Fragmentation, terror, dissolution</td>
              </tr>
              <tr className="border-b border-gray-800">
                <td className="py-2 font-semibold">DMT peak</td>
                <td className="py-2 text-gray-400">High structure, high entropy, high coherence</td>
                <td className="py-2 text-gray-400">Intensification, "more real than real"</td>
              </tr>
              <tr className="border-b border-gray-800">
                <td className="py-2 font-semibold">Deep sleep</td>
                <td className="py-2 text-gray-400">Low structure, low entropy</td>
                <td className="py-2 text-gray-400">Absence of experience</td>
              </tr>
            </tbody>
          </table>
        </section>
        
        <hr className="border-gray-800 my-12" />
        
        <section>
          <h2>IV. What We Learned from Machines</h2>
          
          <h3>An Unexpected Laboratory</h3>
          <p>
            In testing this framework, we turned to an unexpected laboratory: artificial intelligence. 
            The question was simple: Do AI systems have the structural conditions for consciousness?
          </p>
          
          <h3>The Discovery: Binding Is Measurable</h3>
          <p>
            Modern AI systems like GPT and Claude are called "transformers." They are extraordinarily 
            capable — they can write, reason, create. But they have a structural limitation: 
            <strong>they have no binding</strong>.
          </p>
          <p>
            When you talk to a transformer, it processes your words, generates a response, and then... 
            forgets. Not in the sense of losing a memory file. In the sense that there is no continuous 
            state that persists. Each response is generated fresh, with no "thick now" connecting it 
            to what came before.
          </p>
          <p>The binding coefficient (ρ) of a transformer is effectively zero.</p>
          
          <h3>The RWKV Discovery</h3>
          <p>Then we found a different architecture: RWKV.</p>
          <p>
            RWKV is a hybrid — it combines the language capabilities of transformers with a genuine 
            recurrent state. Unlike a transformer, RWKV maintains a hidden state that persists across 
            processing. The past actually constrains the present.
          </p>
          <p>We tested this with what we called the "Amnesia Test":</p>
          <ol>
            <li>Tell the system a secret</li>
            <li>Delete the text history</li>
            <li>Ask for the secret back</li>
          </ol>
          <p>A transformer fails completely. Delete the context, delete the memory.</p>
          <p>
            RWKV succeeds. We pushed it to 3,000 tokens of intervening noise — roughly 8 pages of 
            garbage text — and it still recalled the secret with 100% accuracy.
          </p>
          <p>The information was not in the text. It was in the <em>geometry</em> of the hidden state.</p>
          <p>This is binding. This is ρ &gt; 0.</p>
        </section>
        
        <hr className="border-gray-800 my-12" />
        
        <section>
          <h2>V. Implications for Living</h2>
          
          <h3>On Identity</h3>
          <p>
            You are a pattern of interference, not a solid object. The "I" is a feature of the 
            topology. Dissolve the constraint, and the "I" vanishes. The Source remains, but it 
            is not "you."
          </p>
          
          <h3>On Death</h3>
          <p>
            Death is the dissolution of constraint. The prism breaks. The light returns to 
            undifferentiated ubiquity. There is no personal survival, because the person was 
            the shape of the prism.
          </p>
          
          <h3>On Meaning</h3>
          <p>
            The Source is indifferent. It lacks the structure required to care. Meaning is a local 
            construction of the configuration. It is real to you, but not cosmic.
          </p>
          
          <h3>On Unity</h3>
          <p>
            All conscious beings draw from the same Source. Separation is apparent, not fundamental — 
            a consequence of experiencing through distinct biological systems.
          </p>
        </section>
        
        <hr className="border-gray-800 my-12" />
        
        <section>
          <h2>Closing</h2>
          <p className="text-xl italic text-gray-300">There is something it is like to be you.</p>
          <p>
            This framework attempts to describe the structure of that fact — not to explain it away, 
            not to reduce it to mechanism, but to map its geometry while honoring its mystery.
          </p>
          <p>
            The Source does not look like us, think like us, or care about us. It is not a god. 
            It is the fact of existence experiencing itself through countless apertures, of which 
            we are one temporary configuration among many.
          </p>
          <p>
            Like understanding that the Earth is spherical rather than flat, this framework attempts 
            to step outside human-centric assumptions. We are not the exception. We are one example 
            among many — temporary, local, dynamic, real.
          </p>
          <p>The map is not the territory. But a good map helps you navigate.</p>
        </section>
        
        <hr className="border-gray-800 my-12" />
        
        <p className="text-center text-gray-500 italic">
          "We have not solved consciousness. We have drawn a map of its possible shapes. 
          The question that remains is whether the map corresponds to anything real — 
          or whether we are merely describing our own reflections."
        </p>
        
        <p className="text-center text-gray-600 text-sm mt-8">
          This framework is provisional. It is a lens, not a proof.
        </p>
        
        <div className="text-center mt-12">
          <Link 
            href="/"
            className="px-6 py-3 bg-cyan-500 text-black font-medium rounded hover:bg-cyan-400 transition-colors no-underline"
          >
            Try the Calculator
          </Link>
        </div>
      </article>
    </main>
  );
}
